### ISSUE TITLE
No indication of open source license

### ISSUE THREAD

**Issue by philomory** [jtopjian/terraform-provider-jerakia#2]
I can't help but notice that the software in this repository has no assigned open source license that I can tell (nothing in the README, no LICENSE file, etc). Other software from the Jerakia organization (such as jerakia/jerakia) is under the Apache 2.0 license. Is the intent that this package is licensed the same way, or did you have something else in mind?

**Comment by philomory** [comment]
@jtopjian You're the only person who has ever made a commit to this repository, do you have any input on the license you intended?

**Comment by jtopjian** [comment]
@philomory I've added a license file for Apache.

**Comment by philomory** [comment]
Thanks a bunch!
